### ISSUE TITLE
自转跳转到localhost

### ISSUE THREAD

**Issue by qoderwork** [88250/pipe#74]
compse部署
```
version: '3.1'

services:
  pipetest:
    image: b3log/pipe
    container_name: pipe
    volumes:
      - "./src/pipe.db:/opt/pipe/pipe.db"
    ports:
      - "21313:5897"
```
登陆的时候
http://ec2-*****.ap-east-1.compute.amazonaws.com:21313/
![image](https://user-images.githubusercontent.com/13563637/225835640-4fc5301b-de28-4f37-a956-bbbdbc39b6aa.png)
开始以为跨域问题，参照文档，加上nginx反代还是一样的效果
